### ISSUE TITLE
License images and text

### ISSUE THREAD

**Issue by fl-la** [slimbootloader/slimbootloader.github.io#3]
Hi folks,
I am currently working on some information about various bootloader incl. slimbootloader. What is the license for the documentation site? I found no license statement for pictures, images and figures to be taken from the website.
May you help?

Thanks in advance,
Florian

**Comment by rprangar** [comment]
The source of the documentation is here - https://github.com/slimbootloader/documentation
It uses the same BSD + Patents license - https://github.com/slimbootloader/documentation/blob/master/LICENSE

The github.io repo is for hosting the built files. Hope this helps.

Thanks
Ravi

**Comment by fl-la** [comment]
Ok, thanks a lot for the reply!
